services:
  postgres:
    image: postgres:latest
    container_name: rzkpf_db
    restart: always
    environment:
      POSTGRES_USER: axo-admin
      POSTGRES_PASSWORD: "@inventario25"
      POSTGRES_DB: inventario
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  back:
    build: 
      context: .
      dockerfile: back/Dockerfile
    image: ${DOCKER_REGISTRY-}back
    depends_on:
      - postgres
    environment:
      - APPDATA=/tmp
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=inventario;Username=axo-admin;Password=@inventario25
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "5000:8080"

  nginx:
    image: nginx:latest
    container_name: rzkpf_proxy_nginx
    depends_on:
      - back
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/inventory-api.rozkopf.com:/etc/letsencrypt/live/inventory-api.rozkopf.com:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - /etc/letsencrypt/privkey.pem:/etc/letsencrypt/privkey.pem:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data: