name: CI/CD Deployment

on:
    push:
        branches:
        - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Set up Docker Compose
              uses: docker/setup-compose-action@v2  
            
            - name: Build Docker Image
              run: docker-compose build 
            
            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  git pull origin main
                  cd /home/ec2-user/back
                  docker-compose up -d --build