name: CI/CD Deployment

on:
    push:
        branches:
        - main

jobs:
    Build_and_Deploy:
        runs-on: ubuntu-latest
        environment: EC2
        permissions:
            actions: write
            contents: read
            deployments: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Set up Docker Compose
              run: | 
                sudo rm -rf /usr/local/bin/docker-compose
                curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
                sudo chmod +x /usr/local/bin/docker-compose

            - name: Build Docker Image
              run: docker-compose build --no-cache

            - name: Verify Secrets
              run: |
                echo "EC2_HOST: ${{ secrets.EC2_HOST != '' }}"
                echo "EC2_USER: ${{ secrets.EC2_USER != '' }}"
                echo "SSH_KEY exists: ${{ secrets.EC2_SSH_KEY != '' }}"

            - name: Deploy to EC2
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_SSH_KEY }}
                script: |
                  git config --global init.defaultBranch main
                  
                  if [ ! -d .git ]; then
                    git init .
                    git remote add origin https://github.com/AxoRosskopf/back.git
                    git fetch
                    git branch -m main
                  fi

                  git reset --hard HEAD
                  git clean -fd
                  git pull origin main

                  cd /home/ec2-user/back
                  docker-compose up -d --build