name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    environment: EC2
    permissions:
      actions: write
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install git if not present
            sudo yum install -y git

            # Install Docker Compose if not present
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Create and navigate to project directory
            mkdir -p /home/ec2-user/back
            cd /home/ec2-user/back

            # Git setup and pull
            git config --global init.defaultBranch main
            if [ ! -d .git ]; then
              git init .
              git remote add origin https://github.com/AxoRosskopf/back.git
            fi
            
            git fetch
            git reset --hard origin/main
            git clean -fd

            # Build and run Docker containers
            docker-compose up -d --build