name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  Build_and_Deploy:
    runs-on: ubuntu-latest
    environment: EC2
    permissions:
      actions: write
      contents: read
      deployments: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Install Docker if not present
            if ! command -v docker &> /dev/null; then
              sudo yum update -y
              sudo yum install -y docker
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker $USER
            fi

            # Install Docker Compose if not present
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Generate SSL certificate and key if they do not exist
            if [ ! -f /etc/nginx/ssl/nginx.crt ]; then
              echo "Generating SSL certificate and key..."
              sudo mkdir -p /etc/nginx/ssl
              sudo openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
                -subj "/CN=inventory-api.rozkopf.com" \
                -keyout /etc/nginx/ssl/nginx.key \
                -out /etc/nginx/ssl/nginx.crt
            fi

            # Create and navigate to the project directory
            mkdir -p /home/ec2-user/back
            cd /home/ec2-user/back

            # Git operations
            git config --global init.defaultBranch main
            if [ ! -d .git ]; then
              git init .
              git remote add origin https://github.com/AxoRosskopf/back.git
            fi
            git fetch
            git reset --hard origin/main
            git clean -fd

            # Ensure Docker daemon is running
            sudo systemctl restart docker

            # Build Docker containers and show logs
            sudo docker-compose up -d --build
            echo "Docker Compose logs:"
            sudo docker-compose logs
